name = "SpatialBayesExtremes"
uuid = "23dce541-07d2-483c-a77f-fe2bf38e6d72"
version = "1.0.0-DEV"
authors = ["Marcel Kipping <kipping.marcel@web.de> and contributors"]

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
AbstractMCMC = "5.10.0"
DataFrames = "1"
Distributions = "0.25"
ForwardDiff = "0.10, 1"
GLM = "1.9.0"
LineSearches = "7.3.0"
Optim = "1.10.0"
ProgressMeter = "1.11.0"
SpecialFunctions = "2.4.0"
StatsModels = "0.7"
Turing = "0.36.3"
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
