name = "SpatialBayesExtremes"
uuid = "23dce541-07d2-483c-a77f-fe2bf38e6d72"
authors = ["Marcel Kipping <kipping.marcel@web.de> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
DataFrames = "1"
Distributions = "0.25"
ForwardDiff = "0.10"
Optim = "1.10.0"
ProgressMeter = "1"
Roots = "2.2.2"
SpecialFunctions = "2.4.0"
StatsModels = "0.7"
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
