name = "SpatialBayesExtremes"
uuid = "23dce541-07d2-483c-a77f-fe2bf38e6d72"
authors = ["Marcel Kipping <kipping.marcel@web.de> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
DataFrames = "1"
Distributions = "0.25"
StatsModels = "0.7"
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
