name = "SpatialBayesExtremes"
uuid = "23dce541-07d2-483c-a77f-fe2bf38e6d72"
authors = ["Marcel Kipping <kipping.marcel@web.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
